name: Second Workflow - Start After First Workflow

on:
  push:
    branches:
      - main  # The push from the first workflow triggers this

jobs:
  perform-task:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to get the changes
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run the second task (your actual process)
      - name: Perform Task for Second Workflow
        run: |
          echo "Second workflow has started"
          # Add your task here, e.g., run a Python script or other commands
          python temp.py  # Example of running a script
